import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use',
  description: 'Terms of use for WheelSpinner.',
};

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-gray-900 mb-6">Terms of Use</h1>
      <div className="prose text-gray-600 space-y-6 leading-relaxed">
        <p>Last updated: March 2025</p>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mt-6 mb-2">1. Acceptance</h2>
          <p>By using WheelSpinner, you agree to these Terms of Use. If you do not agree, please do not use the service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mt-6 mb-2">2. Use of the Service</h2>
          <p>WheelSpinner is provided free of charge for personal and educational use. You may not use the service for any unlawful purpose or in any way that could damage, disable, or impair the service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mt-6 mb-2">3. No Warranty</h2>
          <p>WheelSpinner is provided &quot;as is&quot; without warranty of any kind. We do not guarantee the accuracy, completeness, or usefulness of any results generated by the wheel.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mt-6 mb-2">4. Limitation of Liability</h2>
          <p>We shall not be liable for any indirect, incidental, or consequential damages arising out of your use of WheelSpinner.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mt-6 mb-2">5. Changes</h2>
          <p>We reserve the right to modify these terms at any time. Continued use of the service constitutes acceptance of any changes.</p>
        </section>
      </div>
    </div>
  );
}
